config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :hotels do
    resources :rooms
  end

  resources :reservations, only: [:create]

  resources :guests do
    resources :reservations, only: [:index]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_secure_password
  has_many :reservations
  has_many :rooms, through: :reservations
  validates_uniqueness_of :username
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room
  belongs_to :guest
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :reservations
  has_many :guests, through: :reservations

  enum status: ["open", "booked"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_guest

  def current_guest
    @current_guest ||= Guest.find(session[:guest_id]) unless session[:guest_id].nil?
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(guest_params)
    if @guest.save
      session[:guest_id] = @guest.id unless session[:guest_id]
      redirect_to hotels_path
    else
      render :new
    end
  end

  private

  def guest_params
    params.require(:guest).permit(:username, :password, :first_name, :last_name)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ProtectedController
  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
    @rooms = @hotel.rooms
  end
end

app/controllers/protected_controller.rb
class ProtectedController < ApplicationController
  before_action :current_guest?

  def current_guest?
    redirect_to root_path unless current_guest
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ProtectedController
  def index
    @reservations = current_guest.reservations
  end

  def create
    @reservation = Reservation.new(reservation_params)

    if @reservation.save
      @reservation.room.booked!
      redirect_to guest_reservations_path(current_guest)
    else
      redirect_to hotel_room_path(@reservation.room.hotel, @reservation.room)
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:room_id).merge(guest_id: current_guest.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ProtectedController
  def index
    @rooms = Hotel.find(params[:hotel_id]).rooms
  end

  def show
    @room = Room.find(params[:id])
    @guests = @room.guests
    @reservation = Reservation.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session.clear unless session[:guest_id].present?
  end

  def create
    @guest = Guest.find_by(username: params[:session][:username])
    if @guest && @guest.authenticate(params[:session][:password])
      session[:guest_id] = @guest.id
      redirect_to hotels_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session.clear

    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/guests/new.html.erb
<%= form_for(@guest) do |f| %>

  <fieldset>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </fieldset>

  <fieldset>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </fieldset>

  <fieldset>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </fieldset>

  <fieldset>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </fieldset>

  <fieldset>
    <%= f.submit "Create Guest Account" %>
  </fieldset>
<% end %>

app/views/hotels/index.html.erb
<h2>We strive to be a central hub for creating guest reservations at all the following locations:</h2>

<% @hotels.each do |hotel| %>
  <div class="hotel">
    <h3><%= link_to hotel.name, hotel %></h3>
  </div>
<% end %>

app/views/hotels/show.html.erb
<header>
  <h2><%= @hotel.name %> is located in <%= @hotel.location %></h2>
</header>

<main>
  <h3>Below are a list of all rooms available at this hotel.</h3>
  <% @rooms.each do |room| %>
    <ul>
      <li>
        <%= link_to room.number, [@hotel, room] %>
        <p>Status: <%= room.status %></p>
      </li>
    </ul>
  <% end %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel Callbackfornia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar">
      <ul>
      <% if current_guest %>
        <li><%= link_to "Sign Out", logout_path, method: :delete %></li>
        <li><%= link_to "Hotels", hotels_path %></li>
        <li><%= link_to "My Reservations", guest_reservations_path(current_guest) %></li>
      <% else %>
        <li><%= link_to "Sign In", login_path %></li>
        <li><%= link_to "Sign Up", new_guest_path %></li>
      <% end %>
      </ul>
    </nav>

    <h1>Welcome to Hotel Callbackfornia!</h1>

    <%= yield %>
  </body>
</html>

app/views/reservations/index.html.erb
<h2>Below is a list of all your reservations:</h2>

<% @reservations.each do |reservation| %>
<div>
  <h3>Hotel: <%= link_to reservation.room.hotel.name, reservation.room.hotel %></h3>
  <h3>Room: <%= link_to reservation.room.number, hotel_room_path(reservation.room.hotel, reservation.room) %></h3>
  <p>Confirmed on: <%= reservation.created_at %></p>
</div>
<% end %>

app/views/rooms/show.html.erb
<h1>Thanks for your interest in Room <%= @room.number %>!</h1>

<% unless @guests.empty? %>
  <section>
    <h2>Below are all prior reservations that have been made for this room:</h2>

    <% @guests.each do |guest| %>
      <p> <%= "#{guest.first_name} #{guest.last_name}" %> </p>
    <% end %>
  </section>
<% end %>


<section>
  <% if @room.open? %>
    <%= form_for @reservation do |f| %>
      <%= f.hidden_field :room_id, value: @room.id %>
      <%= f.submit %>
    <% end %>
  <% else %>
    <h4>This room is currently booked.</h4>
  <% end %>
</section>